### ISSUE TITLE
causing error with the latest webui version

### ISSUE THREAD

**Issue by harrywang** [datamonet/sd-webui-share#1]
remove the extension, the following error dissapear.
```
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Traceback (most recent call last):
  File "/Users/harrywang/sandbox/stable-diffusion-webui/launch.py", line 356, in <module>
    start()
  File "/Users/harrywang/sandbox/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/Users/harrywang/sandbox/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/Users/harrywang/sandbox/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/harrywang/sandbox/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/Users/harrywang/sandbox/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/Users/harrywang/sandbox/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 44, in <module>
    from huggingface_hub.utils import send_telemetry
ImportError: cannot import name 'send_telemetry' from 'huggingface_hub.utils' (/Users/harrywang/sandbox/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/__init__.py)
```

**Comment by harrywang** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8892
